### ISSUE TITLE
Edit description of a transcript does not save if another transcript is in progress

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-electron#5]
**Describe the bug**

Mentioned by @greggcorp

>if you change the name and description of a completed transcript while another transcript is In Progress, the name change will appear to have saved, then revert back to the original name AND the name change will then apply to the In Progress file.

**To Reproduce**
see description below 

**Expected behavior**
To be able to change name of transcriptions without it reverting back

**Screenshots**
_NA_

**Additional context**
_NA_

**Comment by emettely** [comment]
![bug-dpe](https://user-images.githubusercontent.com/8188418/77619479-9e8e2e00-6f7b-11ea-886b-9b21579dd51d.gif)

**Comment by emettely** [comment]
Seems to be fixed :)
